// 性格表
export const pm_natures = [
    {"CNname":"勤奋","like":"红色","unlike":"红色","up":"—","down":"—"},
    {"CNname":"怕寂寞","like":"红色","unlike":"黄色","up":"攻击","down":"防御"},
    {"CNname":"固执","like":"红色","unlike":"蓝色","up":"攻击","down":"特攻"},
    {"CNname":"顽皮","like":"红色","unlike":"绿色","up":"攻击","down":"特防"},
    {"CNname":"勇敢","like":"红色","unlike":"粉红色","up":"攻击","down":"速度"},
    {"CNname":"大胆","like":"黄色","unlike":"红色","up":"防御","down":"攻击"},
    {"CNname":"坦率","like":"黄色","unlike":"黄色","up":"—","down":"—"},
    {"CNname":"淘气","like":"黄色","unlike":"蓝色","up":"防御","down":"特攻"},
    {"CNname":"乐天","like":"黄色","unlike":"绿色","up":"防御","down":"特防"},
    {"CNname":"悠闲","like":"黄色","unlike":"粉红色","up":"防御","down":"速度"},
    {"CNname":"内敛","like":"蓝色","unlike":"红色","up":"特攻","down":"攻击"},
    {"CNname":"慢吞吞","like":"蓝色","unlike":"黄色","up":"特攻","down":"防御"},
    {"CNname":"害羞","like":"蓝色","unlike":"蓝色","up":"—","down":"—"},
    {"CNname":"马虎","like":"蓝色","unlike":"绿色","up":"特攻","down":"特防"},
    {"CNname":"冷静","like":"蓝色","unlike":"粉红色","up":"特攻","down":"速度"},
    {"CNname":"温和","like":"绿色","unlike":"红色","up":"特防","down":"攻击"},
    {"CNname":"温顺","like":"绿色","unlike":"黄色","up":"特防","down":"防御"},
    {"CNname":"慎重","like":"绿色","unlike":"蓝色","up":"特防","down":"特攻"},
    {"CNname":"浮躁","like":"绿色","unlike":"绿色","up":"—","down":"—"},
    {"CNname":"自大","like":"绿色","unlike":"粉红色","up":"特防","down":"速度"},
    {"CNname":"胆小","like":"粉红色","unlike":"红色","up":"速度","down":"攻击"},
    {"CNname":"急躁","like":"粉红色","unlike":"黄色","up":"速度","down":"防御"},
    {"CNname":"爽朗","like":"粉红色","unlike":"蓝色","up":"速度","down":"特攻"},
    {"CNname":"天真","like":"粉红色","unlike":"绿色","up":"速度","down":"特防"},
    {"CNname":"认真","like":"粉红色","unlike":"粉红色","up":"—","down":"—"},
    
    ]