// 性格表
export const pm_natures = [
    {"CNname ":"勤奋","JPname":"がんばりや","ENname ":"Hardy","up":"—","down":"—","like":"—","unlike":"—"},
    {"CNname ":"怕寂寞","JPname":"さみしがり","ENname ":"Lonely","up":"攻击","down":"防御","like":"辣","unlike":"酸"},
    {"CNname ":"固执","JPname":"いじっぱり","ENname ":"Adamant","up":"攻击","down":"特攻","like":"辣","unlike":"涩"},
    {"CNname ":"顽皮","JPname":"やんちゃ","ENname ":"Naughty","up":"攻击","down":"特防","like":"辣","unlike":"苦"},
    {"CNname ":"勇敢","JPname":"ゆうかん","ENname ":"Brave","up":"攻击","down":"速度","like":"辣","unlike":"甜"},
    {"CNname ":"大胆","JPname":"ずぶとい","ENname ":"Bold","up":"防御","down":"攻击","like":"酸","unlike":"辣"},
    {"CNname ":"坦率","JPname":"すなお","ENname ":"Docile","up":"—","down":"—","like":"—","unlike":"—"},
    {"CNname ":"淘气","JPname":"わんぱく","ENname ":"Impish","up":"防御","down":"特攻","like":"酸","unlike":"涩"},
    {"CNname ":"乐天","JPname":"のうてんき","ENname ":"Lax","up":"防御","down":"特防","like":"酸","unlike":"苦"},
    {"CNname ":"悠闲","JPname":"のんき","ENname ":"Relaxed","up":"防御","down":"速度","like":"酸","unlike":"甜"},
    {"CNname ":"内敛","JPname":"ひかえめ","ENname ":"Modest","up":"特攻","down":"攻击","like":"涩","unlike":"辣"},
    {"CNname ":"慢吞吞","JPname":"おっとり","ENname ":"Mild","up":"特攻","down":"防御","like":"涩","unlike":"酸"},
    {"CNname ":"害羞","JPname":"てれや","ENname ":"Bashful","up":"—","down":"—","like":"—","unlike":"—"},
    {"CNname ":"马虎","JPname":"うっかりや","ENname ":"Rash","up":"特攻","down":"特防","like":"涩","unlike":"苦"},
    {"CNname ":"冷静","JPname":"れいせい","ENname ":"Quiet","up":"特攻","down":"速度","like":"涩","unlike":"甜"},
    {"CNname ":"温和","JPname":"おだやか","ENname ":"Calm","up":"特防","down":"攻击","like":"苦","unlike":"辣"},
    {"CNname ":"温顺","JPname":"おとなしい","ENname ":"Gentle","up":"特防","down":"防御","like":"苦","unlike":"酸"},
    {"CNname ":"慎重","JPname":"しんちょう","ENname ":"Careful","up":"特防","down":"特攻","like":"苦","unlike":"涩"},
    {"CNname ":"浮躁","JPname":"きまぐれ","ENname ":"Quirky","up":"—","down":"—","like":"—","unlike":"—"},
    {"CNname ":"自大","JPname":"なまいき","ENname ":"Sassy","up":"特防","down":"速度","like":"苦","unlike":"甜"},
    {"CNname ":"胆小","JPname":"おくびょう","ENname ":"Timid","up":"速度","down":"攻击","like":"甜","unlike":"辣"},
    {"CNname ":"急躁","JPname":"せっかち","ENname ":"Hasty","up":"速度","down":"防御","like":"甜","unlike":"酸"},
    {"CNname ":"爽朗","JPname":"ようき","ENname ":"Jolly","up":"速度","down":"特攻","like":"甜","unlike":"涩"},
    {"CNname ":"天真","JPname":"むじゃき","ENname ":"Naive","up":"速度","down":"特防","like":"甜","unlike":"苦"},
    {"CNname ":"认真","JPname":"まじめ","ENname ":"Serious","up":"—","down":"—","like":"—","unlike":"—"},
    
    ]