[
    {"cn_name":"拍击","jp_name":"はたく","en_name":"Pound","property":"一般","classfication":"物理","power":"40","hit_probability":"100","PP":"35"},
    {"cn_name":"空手劈","jp_name":"からてチョップ","en_name":"Karate Chop","property":"格斗","classfication":"物理","power":"50","hit_probability":"100","PP":"25"},
    {"cn_name":"连环巴掌","jp_name":"おうふくビンタ","en_name":"Double Slap","property":"一般","classfication":"物理","power":"15","hit_probability":"85","PP":"10"},
    {"cn_name":"连续拳","jp_name":"れんぞくパンチ","en_name":"Comet Punch","property":"一般","classfication":"物理","power":"18","hit_probability":"85","PP":"15"},
    {"cn_name":"百万吨重拳","jp_name":"メガトンパンチ","en_name":"Mega Punch","property":"一般","classfication":"物理","power":"80","hit_probability":"85","PP":"20"},
    {"cn_name":"聚宝功","jp_name":"ネコにこばん","en_name":"Pay Day","property":"一般","classfication":"物理","power":"40","hit_probability":"100","PP":"20"},
    {"cn_name":"火焰拳","jp_name":"ほのおのパンチ","en_name":"Fire Punch","property":"火","classfication":"物理","power":"75","hit_probability":"100","PP":"15"},
    {"cn_name":"冰冻拳","jp_name":"れいとうパンチ","en_name":"Ice Punch","property":"冰","classfication":"物理","power":"75","hit_probability":"100","PP":"15"},
    {"cn_name":"雷电拳","jp_name":"かみなりパンチ","en_name":"Thunder Punch","property":"电","classfication":"物理","power":"75","hit_probability":"100","PP":"15"},
    {"cn_name":"抓","jp_name":"ひっかく","en_name":"Scratch","property":"一般","classfication":"物理","power":"40","hit_probability":"100","PP":"35"},
    {"cn_name":"夹住","jp_name":"はさむ","en_name":"Vice Grip","property":"一般","classfication":"物理","power":"55","hit_probability":"100","PP":"30"},
    {"cn_name":"断头钳","jp_name":"ハサミギロチン","en_name":"Guillotine","property":"一般","classfication":"物理","power":"变化","hit_probability":"变化","PP":"5"},
    {"cn_name":"旋风刀","jp_name":"かまいたち","en_name":"Razor Wind","property":"一般","classfication":"特殊","power":"80","hit_probability":"100","PP":"10"},
    {"cn_name":"剑舞","jp_name":"つるぎのまい","en_name":"Swords Dance","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"20"},
    {"cn_name":"居合斩","jp_name":"いあいぎり","en_name":"Cut","property":"一般","classfication":"物理","power":"50","hit_probability":"95","PP":"30"},
    {"cn_name":"起风","jp_name":"かぜおこし","en_name":"Gust","property":"飞行","classfication":"特殊","power":"40","hit_probability":"100","PP":"35"},
    {"cn_name":"翅膀攻击","jp_name":"つばさでうつ","en_name":"Wing Attack","property":"飞行","classfication":"物理","power":"60","hit_probability":"100","PP":"35"},
    {"cn_name":"吹飞","jp_name":"ふきとばし","en_name":"Whirlwind","property":"一般","classfication":"变化","power":"—","hit_probability":"100","PP":"20"},
    {"cn_name":"飞翔","jp_name":"そらをとぶ","en_name":"Fly","property":"飞行","classfication":"物理","power":"90","hit_probability":"95","PP":"15"},
    {"cn_name":"绑紧","jp_name":"しめつける","en_name":"Bind","property":"一般","classfication":"物理","power":"15","hit_probability":"85","PP":"20"},
    {"cn_name":"摔打","jp_name":"たたきつける","en_name":"Slam","property":"一般","classfication":"物理","power":"80","hit_probability":"75","PP":"20"},
    {"cn_name":"藤鞭","jp_name":"つるのムチ","en_name":"Vine Whip","property":"草","classfication":"物理","power":"45","hit_probability":"100","PP":"25"},
    {"cn_name":"踩踏","jp_name":"ふみつけ","en_name":"Stomp","property":"一般","classfication":"物理","power":"65","hit_probability":"100","PP":"20"},
    {"cn_name":"二连踢","jp_name":"にどげり","en_name":"Double Kick","property":"格斗","classfication":"物理","power":"30","hit_probability":"100","PP":"30"},
    {"cn_name":"百万吨重踢","jp_name":"メガトンキック","en_name":"Mega Kick","property":"一般","classfication":"物理","power":"120","hit_probability":"75","PP":"5"},
    {"cn_name":"飞踢","jp_name":"とびげり","en_name":"Jump Kick","property":"格斗","classfication":"物理","power":"100","hit_probability":"95","PP":"10"},
    {"cn_name":"回旋踢","jp_name":"まわしげり","en_name":"Rolling Kick","property":"格斗","classfication":"物理","power":"60","hit_probability":"85","PP":"15"},
    {"cn_name":"泼沙","jp_name":"すなかけ","en_name":"Sand Attack","property":"地面","classfication":"变化","power":"—","hit_probability":"100","PP":"15"},
    {"cn_name":"头锤","jp_name":"ずつき","en_name":"Headbutt","property":"一般","classfication":"物理","power":"70","hit_probability":"100","PP":"15"},
    {"cn_name":"角撞","jp_name":"つのでつく","en_name":"Horn Attack","property":"一般","classfication":"物理","power":"65","hit_probability":"100","PP":"25"},
    {"cn_name":"乱击","jp_name":"みだれづき","en_name":"Fury Attack","property":"一般","classfication":"物理","power":"15","hit_probability":"85","PP":"20"},
    {"cn_name":"角钻","jp_name":"つのドリル","en_name":"Horn Drill","property":"一般","classfication":"物理","power":"变化","hit_probability":"变化","PP":"5"},
    {"cn_name":"撞击","jp_name":"たいあたり","en_name":"Tackle","property":"一般","classfication":"物理","power":"40","hit_probability":"100","PP":"35"},
    {"cn_name":"泰山压顶","jp_name":"のしかかり","en_name":"Body Slam","property":"一般","classfication":"物理","power":"85","hit_probability":"100","PP":"15"},
    {"cn_name":"紧束","jp_name":"まきつく","en_name":"Wrap","property":"一般","classfication":"物理","power":"15","hit_probability":"90","PP":"20"},
    {"cn_name":"猛撞","jp_name":"とっしん","en_name":"Take Down","property":"一般","classfication":"物理","power":"90","hit_probability":"85","PP":"20"},
    {"cn_name":"大闹一番","jp_name":"あばれる","en_name":"Thrash","property":"一般","classfication":"物理","power":"120","hit_probability":"100","PP":"10"},
    {"cn_name":"舍身冲撞","jp_name":"すてみタックル","en_name":"Double-Edge","property":"一般","classfication":"物理","power":"120","hit_probability":"100","PP":"15"},
    {"cn_name":"摇尾巴","jp_name":"しっぽをふる","en_name":"Tail Whip","property":"一般","classfication":"变化","power":"—","hit_probability":"100","PP":"30"},
    {"cn_name":"毒针","jp_name":"どくばり","en_name":"Poison Sting","property":"毒","classfication":"物理","power":"15","hit_probability":"100","PP":"35"},
    {"cn_name":"双针","jp_name":"ダブルニードル","en_name":"Twineedle","property":"虫","classfication":"物理","power":"25","hit_probability":"100","PP":"20"},
    {"cn_name":"飞弹针","jp_name":"ミサイルばり","en_name":"Pin Missile","property":"虫","classfication":"物理","power":"25","hit_probability":"95","PP":"20"},
    {"cn_name":"瞪眼","jp_name":"にらみつける","en_name":"Leer","property":"一般","classfication":"变化","power":"—","hit_probability":"100","PP":"30"},
    {"cn_name":"咬住","jp_name":"かみつく","en_name":"Bite","property":"恶","classfication":"物理","power":"60","hit_probability":"100","PP":"25"},
    {"cn_name":"叫声","jp_name":"なきごえ","en_name":"Growl","property":"一般","classfication":"变化","power":"—","hit_probability":"100","PP":"40"},
    {"cn_name":"吼叫","jp_name":"ほえる","en_name":"Roar","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"20"},
    {"cn_name":"唱歌","jp_name":"うたう","en_name":"Sing","property":"一般","classfication":"变化","power":"—","hit_probability":"55","PP":"15"},
    {"cn_name":"超音波","jp_name":"ちょうおんぱ","en_name":"Supersonic","property":"一般","classfication":"变化","power":"—","hit_probability":"55","PP":"20"},
    {"cn_name":"音爆","jp_name":"ソニックブーム","en_name":"Sonic Boom","property":"一般","classfication":"特殊","power":"变化","hit_probability":"90","PP":"20"},
    {"cn_name":"定身法","jp_name":"かなしばり","en_name":"Disable","property":"一般","classfication":"变化","power":"—","hit_probability":"100","PP":"20"},
    {"cn_name":"溶解液","jp_name":"ようかいえき","en_name":"Acid","property":"毒","classfication":"特殊","power":"40","hit_probability":"100","PP":"30"},
    {"cn_name":"火花","jp_name":"ひのこ","en_name":"Ember","property":"火","classfication":"特殊","power":"40","hit_probability":"100","PP":"25"},
    {"cn_name":"喷射火焰","jp_name":"かえんほうしゃ","en_name":"Flamethrower","property":"火","classfication":"特殊","power":"90","hit_probability":"100","PP":"15"},
    {"cn_name":"白雾","jp_name":"しろいきり","en_name":"Mist","property":"冰","classfication":"变化","power":"—","hit_probability":"—","PP":"30"},
    {"cn_name":"水枪","jp_name":"みずでっぽう","en_name":"Water Gun","property":"水","classfication":"特殊","power":"40","hit_probability":"100","PP":"25"},
    {"cn_name":"水炮","jp_name":"ハイドロポンプ","en_name":"Hydro Pump","property":"水","classfication":"特殊","power":"110","hit_probability":"80","PP":"5"},
    {"cn_name":"冲浪","jp_name":"なみのり","en_name":"Surf","property":"水","classfication":"特殊","power":"90","hit_probability":"100","PP":"15"},
    {"cn_name":"冰冻光束","jp_name":"れいとうビーム","en_name":"Ice Beam","property":"冰","classfication":"特殊","power":"90","hit_probability":"100","PP":"10"},
    {"cn_name":"暴风雪","jp_name":"ふぶき","en_name":"Blizzard","property":"冰","classfication":"特殊","power":"110","hit_probability":"70","PP":"5"},
    {"cn_name":"幻象光线","jp_name":"サイケこうせん","en_name":"Psybeam","property":"超能力","classfication":"特殊","power":"65","hit_probability":"100","PP":"20"},
    {"cn_name":"泡沫光线","jp_name":"バブルこうせん","en_name":"Bubble Beam","property":"水","classfication":"特殊","power":"65","hit_probability":"100","PP":"20"},
    {"cn_name":"极光束","jp_name":"オーロラビーム","en_name":"Aurora Beam","property":"冰","classfication":"特殊","power":"65","hit_probability":"100","PP":"20"},
    {"cn_name":"破坏光线","jp_name":"はかいこうせん","en_name":"Hyper Beam","property":"一般","classfication":"特殊","power":"150","hit_probability":"90","PP":"5"},
    {"cn_name":"啄","jp_name":"つつく","en_name":"Peck","property":"飞行","classfication":"物理","power":"35","hit_probability":"100","PP":"35"},
    {"cn_name":"啄钻","jp_name":"ドリルくちばし","en_name":"Drill Peck","property":"飞行","classfication":"物理","power":"80","hit_probability":"100","PP":"20"},
    {"cn_name":"地狱翻滚","jp_name":"じごくぐるま","en_name":"Submission","property":"格斗","classfication":"物理","power":"80","hit_probability":"80","PP":"20"},
    {"cn_name":"踢倒","jp_name":"けたぐり","en_name":"Low Kick","property":"格斗","classfication":"物理","power":"变化","hit_probability":"100","PP":"20"},
    {"cn_name":"双倍奉还","jp_name":"カウンター","en_name":"Counter","property":"格斗","classfication":"物理","power":"变化","hit_probability":"100","PP":"20"},
    {"cn_name":"地球上投","jp_name":"ちきゅうなげ","en_name":"Seismic Toss","property":"格斗","classfication":"物理","power":"变化","hit_probability":"100","PP":"20"},
    {"cn_name":"怪力","jp_name":"かいりき","en_name":"Strength","property":"一般","classfication":"物理","power":"80","hit_probability":"100","PP":"15"},
    {"cn_name":"吸取","jp_name":"すいとる","en_name":"Absorb","property":"草","classfication":"特殊","power":"40","hit_probability":"100","PP":"15"},
    {"cn_name":"超级吸取","jp_name":"メガドレイン","en_name":"Mega Drain","property":"草","classfication":"特殊","power":"75","hit_probability":"100","PP":"10"},
    {"cn_name":"寄生种子","jp_name":"やどりぎのタネ","en_name":"Leech Seed","property":"草","classfication":"变化","power":"—","hit_probability":"90","PP":"10"},
    {"cn_name":"生长","jp_name":"せいちょう","en_name":"Growth","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"40"},
    {"cn_name":"飞叶快刀","jp_name":"はっぱカッター","en_name":"Razor Leaf","property":"草","classfication":"物理","power":"55","hit_probability":"95","PP":"25"},
    {"cn_name":"日光束","jp_name":"ソーラービーム","en_name":"Solar Beam","property":"草","classfication":"特殊","power":"200","hit_probability":"100","PP":"10"},
    {"cn_name":"毒粉","jp_name":"どくのこな","en_name":"Poison Powder","property":"毒","classfication":"变化","power":"—","hit_probability":"75","PP":"35"},
    {"cn_name":"麻痹粉","jp_name":"しびれごな","en_name":"Stun Spore","property":"草","classfication":"变化","power":"—","hit_probability":"75","PP":"30"},
    {"cn_name":"催眠粉","jp_name":"ねむりごな","en_name":"Sleep Powder","property":"草","classfication":"变化","power":"—","hit_probability":"75","PP":"15"},
    {"cn_name":"花瓣舞","jp_name":"はなびらのまい","en_name":"Petal Dance","property":"草","classfication":"特殊","power":"120","hit_probability":"100","PP":"10"},
    {"cn_name":"吐丝","jp_name":"いとをはく","en_name":"String Shot","property":"虫","classfication":"变化","power":"—","hit_probability":"95","PP":"40"},
    {"cn_name":"龙之怒","jp_name":"りゅうのいかり","en_name":"Dragon Rage","property":"龙","classfication":"特殊","power":"变化","hit_probability":"100","PP":"10"},
    {"cn_name":"火焰旋涡","jp_name":"ほのおのうず","en_name":"Fire Spin","property":"火","classfication":"特殊","power":"35","hit_probability":"85","PP":"15"},
    {"cn_name":"电击","jp_name":"でんきショック","en_name":"Thunder Shock","property":"电","classfication":"特殊","power":"40","hit_probability":"100","PP":"30"},
    {"cn_name":"十万伏特","jp_name":"１０まんボルト","en_name":"Thunderbolt","property":"电","classfication":"特殊","power":"90","hit_probability":"100","PP":"15"},
    {"cn_name":"电磁波","jp_name":"でんじは","en_name":"Thunder Wave","property":"电","classfication":"变化","power":"—","hit_probability":"90","PP":"20"},
    {"cn_name":"打雷","jp_name":"かみなり","en_name":"Thunder","property":"电","classfication":"特殊","power":"110","hit_probability":"70","PP":"10"},
    {"cn_name":"落石","jp_name":"いわおとし","en_name":"Rock Throw","property":"岩石","classfication":"物理","power":"50","hit_probability":"90","PP":"15"},
    {"cn_name":"地震","jp_name":"じしん","en_name":"Earthquake","property":"地面","classfication":"物理","power":"100","hit_probability":"100","PP":"10"},
    {"cn_name":"地裂","jp_name":"じわれ","en_name":"Fissure","property":"地面","classfication":"物理","power":"变化","hit_probability":"变化","PP":"5"},
    {"cn_name":"挖洞","jp_name":"あなをほる","en_name":"Dig","property":"地面","classfication":"物理","power":"80","hit_probability":"100","PP":"10"},
    {"cn_name":"剧毒","jp_name":"どくどく","en_name":"Toxic","property":"毒","classfication":"变化","power":"—","hit_probability":"90","PP":"10"},
    {"cn_name":"念力","jp_name":"ねんりき","en_name":"Confusion","property":"超能力","classfication":"特殊","power":"50","hit_probability":"100","PP":"25"},
    {"cn_name":"精神强念","jp_name":"サイコキネシス","en_name":"Psychic","property":"超能力","classfication":"特殊","power":"90","hit_probability":"100","PP":"10"},
    {"cn_name":"催眠术","jp_name":"さいみんじゅつ","en_name":"Hypnosis","property":"超能力","classfication":"变化","power":"—","hit_probability":"60","PP":"20"},
    {"cn_name":"瑜伽姿势","jp_name":"ヨガのポーズ","en_name":"Meditate","property":"超能力","classfication":"变化","power":"—","hit_probability":"—","PP":"40"},
    {"cn_name":"高速移动","jp_name":"こうそくいどう","en_name":"Agility","property":"超能力","classfication":"变化","power":"—","hit_probability":"—","PP":"30"},
    {"cn_name":"电光一闪","jp_name":"でんこうせっか","en_name":"Quick Attack","property":"一般","classfication":"物理","power":"40","hit_probability":"100","PP":"30"},
    {"cn_name":"愤怒","jp_name":"いかり","en_name":"Rage","property":"一般","classfication":"物理","power":"20","hit_probability":"100","PP":"20"},
    {"cn_name":"瞬间移动","jp_name":"テレポート","en_name":"Teleport","property":"超能力","classfication":"变化","power":"—","hit_probability":"—","PP":"20"},
    {"cn_name":"黑夜魔影","jp_name":"ナイトヘッド","en_name":"Night Shade","property":"幽灵","classfication":"特殊","power":"变化","hit_probability":"100","PP":"15"},
    {"cn_name":"模仿","jp_name":"ものまね","en_name":"Mimic","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"10"},
    {"cn_name":"刺耳声","jp_name":"いやなおと","en_name":"Screech","property":"一般","classfication":"变化","power":"—","hit_probability":"85","PP":"40"},
    {"cn_name":"影子分身","jp_name":"かげぶんしん","en_name":"Double Team","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"15"},
    {"cn_name":"自我再生","jp_name":"じこさいせい","en_name":"Recover","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"10"},
    {"cn_name":"变硬","jp_name":"かたくなる","en_name":"Harden","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"30"},
    {"cn_name":"变小","jp_name":"ちいさくなる","en_name":"Minimize","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"10"},
    {"cn_name":"烟幕","jp_name":"えんまく","en_name":"Smokescreen","property":"一般","classfication":"变化","power":"—","hit_probability":"100","PP":"20"},
    {"cn_name":"奇异之光","jp_name":"あやしいひかり","en_name":"Confuse Ray","property":"幽灵","classfication":"变化","power":"—","hit_probability":"100","PP":"10"},
    {"cn_name":"缩入壳中","jp_name":"からにこもる","en_name":"Withdraw","property":"水","classfication":"变化","power":"—","hit_probability":"—","PP":"40"},
    {"cn_name":"变圆","jp_name":"まるくなる","en_name":"Defense Curl","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"40"},
    {"cn_name":"屏障","jp_name":"バリアー","en_name":"Barrier","property":"超能力","classfication":"变化","power":"—","hit_probability":"—","PP":"20"},
    {"cn_name":"光墙","jp_name":"ひかりのかべ","en_name":"Light Screen","property":"超能力","classfication":"变化","power":"—","hit_probability":"—","PP":"30"},
    {"cn_name":"黑雾","jp_name":"くろいきり","en_name":"Haze","property":"冰","classfication":"变化","power":"—","hit_probability":"—","PP":"30"},
    {"cn_name":"反射壁","jp_name":"リフレクター","en_name":"Reflect","property":"超能力","classfication":"变化","power":"—","hit_probability":"—","PP":"20"},
    {"cn_name":"聚气","jp_name":"きあいだめ","en_name":"Focus Energy","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"30"},
    {"cn_name":"忍耐","jp_name":"がまん","en_name":"Bide","property":"一般","classfication":"物理","power":"变化","hit_probability":"—","PP":"10"},
    {"cn_name":"挥指","jp_name":"ゆびをふる","en_name":"Metronome","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"10"},
    {"cn_name":"鹦鹉学舌","jp_name":"オウムがえし","en_name":"Mirror Move","property":"飞行","classfication":"变化","power":"—","hit_probability":"—","PP":"20"},
    {"cn_name":"自爆","jp_name":"じばく","en_name":"Self-Destruct","property":"一般","classfication":"物理","power":"200","hit_probability":"100","PP":"5"},
    {"cn_name":"炸蛋","jp_name":"タマゴばくだん","en_name":"Egg Bomb","property":"一般","classfication":"物理","power":"100","hit_probability":"75","PP":"10"},
    {"cn_name":"舌舔","jp_name":"したでなめる","en_name":"Lick","property":"幽灵","classfication":"物理","power":"30","hit_probability":"100","PP":"30"},
    {"cn_name":"浊雾","jp_name":"スモッグ","en_name":"Smog","property":"毒","classfication":"特殊","power":"30","hit_probability":"70","PP":"20"},
    {"cn_name":"污泥攻击","jp_name":"ヘドロこうげき","en_name":"Sludge","property":"毒","classfication":"特殊","power":"65","hit_probability":"100","PP":"20"},
    {"cn_name":"骨棒","jp_name":"ホネこんぼう","en_name":"Bone Club","property":"地面","classfication":"物理","power":"65","hit_probability":"85","PP":"20"},
    {"cn_name":"大字爆炎","jp_name":"だいもんじ","en_name":"Fire Blast","property":"火","classfication":"特殊","power":"110","hit_probability":"85","PP":"5"},
    {"cn_name":"攀瀑","jp_name":"たきのぼり","en_name":"Waterfall","property":"水","classfication":"物理","power":"80","hit_probability":"100","PP":"15"},
    {"cn_name":"贝壳夹击","jp_name":"からではさむ","en_name":"Clamp","property":"水","classfication":"物理","power":"35","hit_probability":"85","PP":"15"},
    {"cn_name":"高速星星","jp_name":"スピードスター","en_name":"Swift","property":"一般","classfication":"特殊","power":"60","hit_probability":"—","PP":"20"},
    {"cn_name":"火箭头锤","jp_name":"ロケットずつき","en_name":"Skull Bash","property":"一般","classfication":"物理","power":"130","hit_probability":"100","PP":"10"},
    {"cn_name":"尖刺加农炮","jp_name":"とげキャノン","en_name":"Spike Cannon","property":"一般","classfication":"物理","power":"20","hit_probability":"100","PP":"15"},
    {"cn_name":"缠绕","jp_name":"からみつく","en_name":"Constrict","property":"一般","classfication":"物理","power":"10","hit_probability":"100","PP":"35"},
    {"cn_name":"瞬间失忆","jp_name":"ドわすれ","en_name":"Amnesia","property":"超能力","classfication":"变化","power":"—","hit_probability":"—","PP":"20"},
    {"cn_name":"折弯汤匙","jp_name":"スプーンまげ","en_name":"Kinesis","property":"超能力","classfication":"变化","power":"—","hit_probability":"80","PP":"15"},
    {"cn_name":"生蛋","jp_name":"タマゴうみ","en_name":"Soft-Boiled","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"10"},
    {"cn_name":"飞膝踢","jp_name":"とびひざげり","en_name":"High Jump Kick","property":"格斗","classfication":"物理","power":"130","hit_probability":"90","PP":"10"},
    {"cn_name":"大蛇瞪眼","jp_name":"へびにらみ","en_name":"Glare","property":"一般","classfication":"变化","power":"—","hit_probability":"100","PP":"30"},
    {"cn_name":"食梦","jp_name":"ゆめくい","en_name":"Dream Eater","property":"超能力","classfication":"特殊","power":"100","hit_probability":"100","PP":"15"},
    {"cn_name":"毒瓦斯","jp_name":"どくガス","en_name":"Poison Gas","property":"毒","classfication":"变化","power":"—","hit_probability":"90","PP":"40"},
    {"cn_name":"投球","jp_name":"たまなげ","en_name":"Barrage","property":"一般","classfication":"物理","power":"15","hit_probability":"85","PP":"20"},
    {"cn_name":"吸血","jp_name":"きゅうけつ","en_name":"Leech Life","property":"虫","classfication":"物理","power":"80","hit_probability":"100","PP":"10"},
    {"cn_name":"恶魔之吻","jp_name":"あくまのキッス","en_name":"Lovely Kiss","property":"一般","classfication":"变化","power":"—","hit_probability":"75","PP":"10"},
    {"cn_name":"神鸟猛击","jp_name":"ゴッドバード","en_name":"Sky Attack","property":"飞行","classfication":"物理","power":"200","hit_probability":"90","PP":"5"},
    {"cn_name":"变身","jp_name":"へんしん","en_name":"Transform","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"10"},
    {"cn_name":"泡沫","jp_name":"あわ","en_name":"Bubble","property":"水","classfication":"特殊","power":"40","hit_probability":"100","PP":"30"},
    {"cn_name":"迷昏拳","jp_name":"ピヨピヨパンチ","en_name":"Dizzy Punch","property":"一般","classfication":"物理","power":"70","hit_probability":"100","PP":"10"},
    {"cn_name":"蘑菇孢子","jp_name":"キノコのほうし","en_name":"Spore","property":"草","classfication":"变化","power":"—","hit_probability":"100","PP":"15"},
    {"cn_name":"闪光","jp_name":"フラッシュ","en_name":"Flash","property":"一般","classfication":"变化","power":"—","hit_probability":"100","PP":"20"},
    {"cn_name":"精神波","jp_name":"サイコウェーブ","en_name":"Psywave","property":"超能力","classfication":"特殊","power":"变化","hit_probability":"100","PP":"15"},
    {"cn_name":"跃起","jp_name":"はねる","en_name":"Splash","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"40"},
    {"cn_name":"溶化","jp_name":"とける","en_name":"Acid Armor","property":"毒","classfication":"变化","power":"—","hit_probability":"—","PP":"20"},
    {"cn_name":"蟹钳锤","jp_name":"クラブハンマー","en_name":"Crabhammer","property":"水","classfication":"物理","power":"100","hit_probability":"90","PP":"10"},
    {"cn_name":"大爆炸","jp_name":"だいばくはつ","en_name":"Explosion","property":"一般","classfication":"物理","power":"250","hit_probability":"100","PP":"5"},
    {"cn_name":"乱抓","jp_name":"みだれひっかき","en_name":"Fury Swipes","property":"一般","classfication":"物理","power":"18","hit_probability":"80","PP":"15"},
    {"cn_name":"骨头回力镖","jp_name":"ホネブーメラン","en_name":"Bonemerang","property":"地面","classfication":"物理","power":"50","hit_probability":"90","PP":"10"},
    {"cn_name":"睡觉","jp_name":"ねむる","en_name":"Rest","property":"超能力","classfication":"变化","power":"—","hit_probability":"—","PP":"10"},
    {"cn_name":"岩崩","jp_name":"いわなだれ","en_name":"Rock Slide","property":"岩石","classfication":"物理","power":"75","hit_probability":"90","PP":"10"},
    {"cn_name":"必杀门牙","jp_name":"ひっさつまえば","en_name":"Hyper Fang","property":"一般","classfication":"物理","power":"80","hit_probability":"90","PP":"15"},
    {"cn_name":"棱角化","jp_name":"かくばる","en_name":"Sharpen","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"30"},
    {"cn_name":"纹理","jp_name":"テクスチャー","en_name":"Conversion","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"30"},
    {"cn_name":"三重攻击","jp_name":"トライアタック","en_name":"Tri Attack","property":"一般","classfication":"特殊","power":"80","hit_probability":"100","PP":"10"},
    {"cn_name":"愤怒门牙","jp_name":"いかりのまえば","en_name":"Super Fang","property":"一般","classfication":"物理","power":"变化","hit_probability":"90","PP":"10"},
    {"cn_name":"劈开","jp_name":"きりさく","en_name":"Slash","property":"一般","classfication":"物理","power":"70","hit_probability":"100","PP":"20"},
    {"cn_name":"替身","jp_name":"みがわり","en_name":"Substitute","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"10"},
    {"cn_name":"挣扎","jp_name":"わるあがき","en_name":"Struggle","property":"一般","classfication":"物理","power":"50","hit_probability":"—","PP":"—"},
    {"cn_name":"守住","jp_name":"まもる","en_name":"Protect","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"10"},
    {"cn_name":"污泥炸弹","jp_name":"ヘドロばくだん","en_name":"Sludge Bomb","property":"毒","classfication":"特殊","power":"90","hit_probability":"100","PP":"10"},
    {"cn_name":"逆鳞","jp_name":"げきりん","en_name":"Outrage","property":"龙","classfication":"物理","power":"120","hit_probability":"100","PP":"15"},
    {"cn_name":"超级角击","jp_name":"メガホーン","en_name":"Megahorn","property":"虫","classfication":"物理","power":"120","hit_probability":"85","PP":"10"},
    {"cn_name":"再来一次","jp_name":"アンコール","en_name":"Encore","property":"一般","classfication":"变化","power":"—","hit_probability":"100","PP":"5"},
    {"cn_name":"铁尾","jp_name":"アイアンテール","en_name":"Iron Tail","property":"钢","classfication":"物理","power":"100","hit_probability":"75","PP":"15"},
    {"cn_name":"咬碎","jp_name":"かみくだく","en_name":"Crunch","property":"恶","classfication":"物理","power":"80","hit_probability":"100","PP":"15"},
    {"cn_name":"镜面反射","jp_name":"ミラーコート","en_name":"Mirror Coat","property":"超能力","classfication":"特殊","power":"变化","hit_probability":"100","PP":"20"},
    {"cn_name":"暗影球","jp_name":"シャドーボール","en_name":"Shadow Ball","property":"幽灵","classfication":"特殊","power":"80","hit_probability":"100","PP":"15"},
    {"cn_name":"击掌奇袭","jp_name":"ねこだまし","en_name":"Fake Out","property":"一般","classfication":"物理","power":"40","hit_probability":"100","PP":"10"},
    {"cn_name":"热风","jp_name":"ねっぷう","en_name":"Heat Wave","property":"火","classfication":"特殊","power":"95","hit_probability":"90","PP":"10"},
    {"cn_name":"鬼火","jp_name":"おにび","en_name":"Will-O-Wisp","property":"火","classfication":"变化","power":"—","hit_probability":"85","PP":"15"},
    {"cn_name":"硬撑","jp_name":"からげんき","en_name":"Facade","property":"一般","classfication":"物理","power":"70","hit_probability":"100","PP":"20"},
    {"cn_name":"挑衅","jp_name":"ちょうはつ","en_name":"Taunt","property":"恶","classfication":"变化","power":"—","hit_probability":"100","PP":"20"},
    {"cn_name":"帮助","jp_name":"てだすけ","en_name":"Helping Hand","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"20"},
    {"cn_name":"蛮力","jp_name":"ばかぢから","en_name":"Superpower","property":"格斗","classfication":"物理","power":"120","hit_probability":"100","PP":"5"},
    {"cn_name":"劈瓦","jp_name":"かわらわり","en_name":"Brick Break","property":"格斗","classfication":"物理","power":"75","hit_probability":"100","PP":"15"},
    {"cn_name":"哈欠","jp_name":"あくび","en_name":"Yawn","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"10"},
    {"cn_name":"健美","jp_name":"ビルドアップ","en_name":"Bulk Up","property":"格斗","classfication":"变化","power":"—","hit_probability":"—","PP":"20"},
    {"cn_name":"冥想","jp_name":"めいそう","en_name":"Calm Mind","property":"超能力","classfication":"变化","power":"—","hit_probability":"—","PP":"20"},
    {"cn_name":"羽栖","jp_name":"はねやすめ","en_name":"Roost","property":"飞行","classfication":"变化","power":"—","hit_probability":"—","PP":"10"},
    {"cn_name":"佯攻","jp_name":"フェイント","en_name":"Feint","property":"一般","classfication":"物理","power":"50","hit_probability":"100","PP":"10"},
    {"cn_name":"急速折返","jp_name":"とんぼがえり","en_name":"U-turn","property":"虫","classfication":"物理","power":"70","hit_probability":"100","PP":"20"},
    {"cn_name":"突袭","jp_name":"ふいうち","en_name":"Sucker Punch","property":"恶","classfication":"物理","power":"70","hit_probability":"100","PP":"5"},
    {"cn_name":"闪焰冲锋","jp_name":"フレアドライブ","en_name":"Flare Blitz","property":"火","classfication":"物理","power":"120","hit_probability":"100","PP":"15"},
    {"cn_name":"毒击","jp_name":"どくづき","en_name":"Poison Jab","property":"毒","classfication":"物理","power":"80","hit_probability":"100","PP":"20"},
    {"cn_name":"恶之波动","jp_name":"あくのはどう","en_name":"Dark Pulse","property":"恶","classfication":"特殊","power":"80","hit_probability":"100","PP":"15"},
    {"cn_name":"空气斩","jp_name":"エアスラッシュ","en_name":"Air Slash","property":"飞行","classfication":"特殊","power":"75","hit_probability":"95","PP":"15"},
    {"cn_name":"十字剪","jp_name":"シザークロス","en_name":"X-Scissor","property":"虫","classfication":"物理","power":"80","hit_probability":"100","PP":"15"},
    {"cn_name":"虫鸣","jp_name":"むしのさざめき","en_name":"Bug Buzz","property":"虫","classfication":"特殊","power":"90","hit_probability":"100","PP":"10"},
    {"cn_name":"龙之波动","jp_name":"りゅうのはどう","en_name":"Dragon Pulse","property":"龙","classfication":"特殊","power":"85","hit_probability":"100","PP":"10"},
    {"cn_name":"诡计","jp_name":"わるだくみ","en_name":"Nasty Plot","property":"恶","classfication":"变化","power":"—","hit_probability":"—","PP":"20"},
    {"cn_name":"冰砾","jp_name":"こおりのつぶて","en_name":"Ice Shard","property":"冰","classfication":"物理","power":"40","hit_probability":"100","PP":"30"},
    {"cn_name":"加农光炮","jp_name":"ラスターカノン","en_name":"Flash Cannon","property":"钢","classfication":"特殊","power":"80","hit_probability":"100","PP":"10"},
    {"cn_name":"强力鞭打","jp_name":"パワーウィップ","en_name":"Power Whip","property":"草","classfication":"物理","power":"120","hit_probability":"85","PP":"10"},
    {"cn_name":"隐形岩","jp_name":"ステルスロック","en_name":"Stealth Rock","property":"岩石","classfication":"变化","power":"—","hit_probability":"—","PP":"20"},
    {"cn_name":"水流喷射","jp_name":"アクアジェット","en_name":"Aqua Jet","property":"水","classfication":"物理","power":"40","hit_probability":"100","PP":"20"},
    {"cn_name":"蝶舞","jp_name":"ちょうのまい","en_name":"Quiver Dance","property":"虫","classfication":"变化","power":"—","hit_probability":"—","PP":"20"},
    {"cn_name":"重磅冲撞","jp_name":"ヘビーボンバー","en_name":"Heavy Slam","property":"钢","classfication":"物理","power":"变化","hit_probability":"100","PP":"10"},
    {"cn_name":"欺诈","jp_name":"イカサマ","en_name":"Foul Play","property":"恶","classfication":"物理","power":"95","hit_probability":"100","PP":"15"},
    {"cn_name":"清除之烟","jp_name":"クリアスモッグ","en_name":"Clear Smog","property":"毒","classfication":"特殊","power":"50","hit_probability":"—","PP":"15"},
    {"cn_name":"热水","jp_name":"ねっとう","en_name":"Scald","property":"水","classfication":"特殊","power":"80","hit_probability":"100","PP":"15"},
    {"cn_name":"破壳","jp_name":"からをやぶる","en_name":"Shell Smash","property":"一般","classfication":"变化","power":"—","hit_probability":"—","PP":"15"},
    {"cn_name":"龙尾","jp_name":"ドラゴンテール","en_name":"Dragon Tail","property":"龙","classfication":"物理","power":"60","hit_probability":"90","PP":"10"},
    {"cn_name":"直冲钻","jp_name":"ドリルライナー","en_name":"Drill Run","property":"地面","classfication":"物理","power":"80","hit_probability":"95","PP":"10"},
    {"cn_name":"嬉闹","jp_name":"じゃれつく","en_name":"Play Rough","property":"妖精","classfication":"物理","power":"90","hit_probability":"90","PP":"15"},
    {"cn_name":"月亮之力","jp_name":"ムーンフォース","en_name":"Moonblast","property":"妖精","classfication":"特殊","power":"95","hit_probability":"100","PP":"15"},
    {"cn_name":"魔法闪耀","jp_name":"マジカルシャイン","en_name":"Dazzling Gleam","property":"妖精","classfication":"特殊","power":"80","hit_probability":"100","PP":"10"},
    {"cn_name":"电电加速","jp_name":"ばちばちアクセル","en_name":"Zippy Zap","property":"电","classfication":"物理","power":"50","hit_probability":"100","PP":"15"},
    {"cn_name":"滔滔冲浪","jp_name":"ざぶざぶサーフ","en_name":"Splishy Splash","property":"水","classfication":"特殊","power":"90","hit_probability":"100","PP":"15"},
    {"cn_name":"飘飘坠落","jp_name":"ふわふわフォール","en_name":"Floaty Fall","property":"飞行","classfication":"物理","power":"90","hit_probability":"95","PP":"15"},
    {"cn_name":"闪闪雷光","jp_name":"ピカピカサンダー","en_name":"Pika Papow","property":"电","classfication":"特殊","power":"变化","hit_probability":"—","PP":"20"},
    {"cn_name":"活活气泡","jp_name":"いきいきバブル","en_name":"Bouncy Bubble","property":"水","classfication":"特殊","power":"90","hit_probability":"100","PP":"15"},
    {"cn_name":"麻麻电击","jp_name":"びりびりエレキ","en_name":"Buzzy Blitz","property":"电","classfication":"特殊","power":"90","hit_probability":"100","PP":"15"},
    {"cn_name":"熊熊火爆","jp_name":"めらめらバーン","en_name":"Sizzly Slide","property":"火","classfication":"物理","power":"90","hit_probability":"100","PP":"15"},
    {"cn_name":"哗哗气场","jp_name":"どばどばオーラ","en_name":"Glitzy Glow","property":"超能力","classfication":"特殊","power":"90","hit_probability":"100","PP":"15"},
    {"cn_name":"坏坏领域","jp_name":"わるわるゾーン","en_name":"Baddy Bad","property":"恶","classfication":"特殊","power":"90","hit_probability":"100","PP":"15"},
    {"cn_name":"茁茁轰炸","jp_name":"すくすくボンバー","en_name":"Sappy Seed","property":"草","classfication":"物理","power":"90","hit_probability":"100","PP":"15"},
    {"cn_name":"冰冰霜冻","jp_name":"こちこちフロスト","en_name":"Freezy Frost","property":"冰","classfication":"特殊","power":"90","hit_probability":"100","PP":"15"},
    {"cn_name":"亮亮风暴","jp_name":"きらきらストーム","en_name":"Sparkly Swirl","property":"妖精","classfication":"特殊","power":"90","hit_probability":"100","PP":"15"},
    {"cn_name":"砰砰击破","jp_name":"ブイブイブレイク","en_name":"Veevee Volley","property":"一般","classfication":"物理","power":"变化","hit_probability":"—","PP":"20"},
    {"cn_name":"钢拳双击","jp_name":"ダブルパンツァー","en_name":"Double Iron Bash","property":"钢","classfication":"物理","power":"60","hit_probability":"100","PP":"5"},
    
    ]